#A. UNA LLAVE QUE SE HABRE 4 HORAS, VIERTE 1200 LITROS DE AGUA.REALIZAR UN PROGRAMA QUE CALCULE CUANTA AGUA VIERTE LA LLAVE EN CUALQUIER NUMERO DE HORAS. 

print("A. UNA LLAVE QUE SE HABRE 4 HORAS, VIERTE 1200 LITROS DE AGUA. REALIZAR UN PROGRAMA QUE CALCULE CUANTA AGUA VIERTE LA LLAVE EN CUALQUIER NUMERO DE HORAS. ")

hora=float(input('Escribe horas abiertas de la llave): '))

a=1200/4

total=hora*a

print("el agua vertida es:",str(total),"litros")


